(library
 (name redis_test)
 (libraries async async_extra.async_bus async_unix available_ephemeral_port
   core_kernel.bus core expect_test_helpers_core core_kernel.iobuf redis
   redis_helpers core_kernel.weak_pointer)
 (preprocess
  (pps ppx_jane ppx_nix))
 (preprocessor_deps %{workspace_root}/sysdeps/nix/valkey_9_0.sysdep.sexp))
